# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'animationNavigationBarApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'LUKeychainAccess', '~> 1.2'
  # Pods for animationNavigationBarApp

  target 'animationNavigationBarAppTests' do
    inherit! :search_paths
    # Pods for testing
pod 'LUKeychainAccess', '~> 1.2'
  end

  target 'animationNavigationBarAppUITests' do
    inherit! :search_paths
pod 'LUKeychainAccess', '~> 1.2'
    # Pods for testing
  end

end
